= Introduction
The goal of this document is to provide guidance on how to write for the People's Liberation Training Committee. The style guide aims to cover everything from web based articles and features to training manuals and handouts, providing clear guidelines on design, voice, and content.

== Sections
=== Grammar
The first section will cover grammar and other technical aspects of writing. Consistent and correct grammar in each published language is important when communicating and teaching.

=== Voice
How we write to our audience is just as important as what we write. This section will cover our voice, audience, and writing sytle. Who we are writing to and how we say it.

=== Book Design
This section will cover the layout and formatting of books, manuals, and other print and print style publications. This will cover student and instructor manuals, as well as physical handouts.

=== Web Desgin
This section will cover the layout and formatting of web based publications. While manuals will also be published on the web, this section is focused on web pages, articles, slide decks, and other web native content.